# Generated by Django 4.2.5 on 2023-11-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menuitem_rename_title_menu_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='Inventory',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
