# Generated by Django 4.2.5 on 2023-11-23 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_menuitem_inventory_alter_menuitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='Name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='Title',
            new_name='title',
        ),
    ]
