# Generated by Django 4.2.5 on 2023-11-23 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_menu_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='Inventory',
            new_name='inventory',
        ),
    ]
