# Generated by Django 4.2.5 on 2023-11-23 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_rename_inventory_menuitem_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
