# Generated by Django 4.2.5 on 2023-11-23 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_delete_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='Noofguests',
            new_name='no_of_guests',
        ),
    ]
